services:
  - type: web
    name: ecommerce-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://e-commerce-website-backend-6xku.onrender.com/api/v1
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        value: your-stripe-publishable-key